### ISSUE TITLE
载入插件错误

### ISSUE THREAD

**Issue by aazhaoyoukino** [HDTianRu/TianRu-plugin#1]
![GFY@W`}{HC 3K8HI9QPP@01](https://github.com/HDTianRu/TianRu-plugin/assets/125206670/176d7278-79c2-401b-9bc6-9042529bcd20)
一开始以为是依赖问题没在意，重装依赖后发现不是，因为是小白，自己查阅资料解决无果后只能来这里提问了

**Comment by HDTianRu** [comment]
啊，这个是因为我没有把依赖写到package.json里，导致无法自动安装对应的依赖，我这边由于其他插件安装了这个依赖，导致没发现，一会儿把这玩意儿加到package.json里，就能用pnpm install -P安装依赖了

**Comment by HDTianRu** [comment]
可以了，更新插件，然后在云崽目录pnpm install -P（根据自己情况使用npm或pnpm）应该就行了
